# Generated by Django 5.1 on 2024-08-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egyanportal', '0002_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('program', models.CharField(max_length=200)),
                ('Branch', models.CharField(max_length=200)),
                ('Year', models.IntegerField()),
                ('subject', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=200)),
                ('new_file', models.FileField(upload_to='myimage')),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('program', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=300)),
                ('contactno', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=200)),
                ('Subject', models.CharField(max_length=300)),
                ('comp', models.CharField(max_length=1000)),
                ('reqdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=500)),
                ('contactno', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=200)),
                ('enq', models.CharField(max_length=1000)),
                ('enqdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('program', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=300)),
                ('contactno', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=200)),
                ('Subject', models.CharField(max_length=300)),
                ('feed', models.CharField(max_length=1000)),
                ('reqdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='lecture',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('program', models.CharField(max_length=200)),
                ('Branch', models.CharField(max_length=200)),
                ('Year', models.IntegerField()),
                ('subject', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usm',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('program', models.CharField(max_length=200)),
                ('Branch', models.CharField(max_length=200)),
                ('Year', models.IntegerField()),
                ('subject', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=200)),
                ('new_file', models.FileField(upload_to='myimage')),
            ],
        ),
    ]
