# Generated by Django 5.0.6 on 2024-08-31 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egyanportal', '0003_assignment_complaints_enquiry_feedbacks_lecture_usm'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='New_file',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='registration',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
