# Generated by Django 5.0.6 on 2024-08-31 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egyanportal', '0004_complaints_status_feedbacks_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='gender',
        ),
    ]
