# Generated by Django 5.0.6 on 2024-09-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egyanportal', '0008_alter_feedbacks_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='New_file',
            field=models.ImageField(null=True, upload_to='myimage'),
        ),
    ]
