# Generated by Django 5.0.6 on 2024-09-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egyanportal', '0009_alter_registration_new_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='New_file',
            field=models.ImageField(blank=True, null=True, upload_to='myimage'),
        ),
    ]
